### ISSUE TITLE
Write a utility/script for versioning

### ISSUE THREAD

**Issue by clandest** [MASQ-Project/MASQ-Node-issues#91] opened 2019-09-22 15:29 UTC
It should:

update the version number in all Cargo.toml files

update the version number in package.json files

update the version number in other places that need it

add the tag to the master branch

DON'T automatically push the changes or the tag, only commit them locally.

**Comment by utkarshg6** [comment] 2023-03-15 10:12
This is a duplicate of #679, except the tagging feature.

I'm unsure if adding the git commands inside the script is a good idea or not?

The part that I don't understand about this card is that which `package.json` files are we talking over here.

**Closed as not planned** 2023-03-31 16:31 UTC
Labels: wontfix, story
